### ISSUE TITLE
implement i18n

### ISSUE THREAD

**Issue by sangdth** [websitesieutoc/nextjs-template#44]
Each one should be **SEPARATED PR**! ⚠️ 

- [x] this one should be done after the migration of pages => app router #51 
- [x] update the middleware so it can rewrite the path with /en/ or /vi/  #73 
- [x] update the structure of codebase under the `[locale]` slug #73 
- [x] render the page according to current locale #73 
- [x] update the Page editor to have ability of changing language option

https://nextjs.org/docs/app/building-your-application/routing/internationalization
